/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeroRouteImport } from './routes/hero'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDocumentationRouteImport } from './routes/_app/documentation'
import { Route as AppArticlesRouteImport } from './routes/_app/articles'
import { Route as AppPermissionsIndexRouteImport } from './routes/_app/permissions/index'
import { Route as AppArticlesIndexRouteImport } from './routes/_app/articles/index'
import { Route as AppPlaygroundNav12RouteImport } from './routes/_app/playground/nav1-2'
import { Route as AppPlaygroundNav112RouteImport } from './routes/_app/playground/nav1-1-2'
import { Route as AppPlaygroundNav111RouteImport } from './routes/_app/playground/nav1-1-1'
import { Route as AppPlaygroundNav11RouteImport } from './routes/_app/playground/nav1-1'
import { Route as AppPermissionsUsersRouteImport } from './routes/_app/permissions/users'
import { Route as AppPermissionsRolesRouteImport } from './routes/_app/permissions/roles'
import { Route as AppArticlesCreateRouteImport } from './routes/_app/articles/create'
import { Route as AppPermissionsUsersIndexRouteImport } from './routes/_app/permissions/users/index'
import { Route as AppPermissionsRolesIndexRouteImport } from './routes/_app/permissions/roles/index'
import { Route as AppArticlesArticleIdIndexRouteImport } from './routes/_app/articles/$articleId.index'
import { Route as AppPermissionsUsersCreateRouteImport } from './routes/_app/permissions/users/create'
import { Route as AppPermissionsRolesCreateRouteImport } from './routes/_app/permissions/roles/create'
import { Route as AppArticlesArticleIdEditRouteImport } from './routes/_app/articles/$articleId.edit'
import { Route as AppPermissionsUsersUserIdEditRouteImport } from './routes/_app/permissions/users/$userId.edit'
import { Route as AppPermissionsRolesRoleIdEditRouteImport } from './routes/_app/permissions/roles/$roleId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroRoute = HeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsIndexRoute = AppPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppArticlesRoute,
} as any)
const AppPlaygroundNav12Route = AppPlaygroundNav12RouteImport.update({
  id: '/playground/nav1-2',
  path: '/playground/nav1-2',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundNav112Route = AppPlaygroundNav112RouteImport.update({
  id: '/playground/nav1-1-2',
  path: '/playground/nav1-1-2',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundNav111Route = AppPlaygroundNav111RouteImport.update({
  id: '/playground/nav1-1-1',
  path: '/playground/nav1-1-1',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundNav11Route = AppPlaygroundNav11RouteImport.update({
  id: '/playground/nav1-1',
  path: '/playground/nav1-1',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsUsersRoute = AppPermissionsUsersRouteImport.update({
  id: '/permissions/users',
  path: '/permissions/users',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRolesRoute = AppPermissionsRolesRouteImport.update({
  id: '/permissions/roles',
  path: '/permissions/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesCreateRoute = AppArticlesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppArticlesRoute,
} as any)
const AppPermissionsUsersIndexRoute =
  AppPermissionsUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPermissionsUsersRoute,
  } as any)
const AppPermissionsRolesIndexRoute =
  AppPermissionsRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPermissionsRolesRoute,
  } as any)
const AppArticlesArticleIdIndexRoute =
  AppArticlesArticleIdIndexRouteImport.update({
    id: '/$articleId/',
    path: '/$articleId/',
    getParentRoute: () => AppArticlesRoute,
  } as any)
const AppPermissionsUsersCreateRoute =
  AppPermissionsUsersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppPermissionsUsersRoute,
  } as any)
const AppPermissionsRolesCreateRoute =
  AppPermissionsRolesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppPermissionsRolesRoute,
  } as any)
const AppArticlesArticleIdEditRoute =
  AppArticlesArticleIdEditRouteImport.update({
    id: '/$articleId/edit',
    path: '/$articleId/edit',
    getParentRoute: () => AppArticlesRoute,
  } as any)
const AppPermissionsUsersUserIdEditRoute =
  AppPermissionsUsersUserIdEditRouteImport.update({
    id: '/$userId/edit',
    path: '/$userId/edit',
    getParentRoute: () => AppPermissionsUsersRoute,
  } as any)
const AppPermissionsRolesRoleIdEditRoute =
  AppPermissionsRolesRoleIdEditRouteImport.update({
    id: '/$roleId/edit',
    path: '/$roleId/edit',
    getParentRoute: () => AppPermissionsRolesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/hero': typeof HeroRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/articles': typeof AppArticlesRouteWithChildren
  '/documentation': typeof AppDocumentationRoute
  '/settings': typeof AppSettingsRoute
  '/articles/create': typeof AppArticlesCreateRoute
  '/permissions/roles': typeof AppPermissionsRolesRouteWithChildren
  '/permissions/users': typeof AppPermissionsUsersRouteWithChildren
  '/playground/nav1-1': typeof AppPlaygroundNav11Route
  '/playground/nav1-1-1': typeof AppPlaygroundNav111Route
  '/playground/nav1-1-2': typeof AppPlaygroundNav112Route
  '/playground/nav1-2': typeof AppPlaygroundNav12Route
  '/articles/': typeof AppArticlesIndexRoute
  '/permissions/': typeof AppPermissionsIndexRoute
  '/articles/$articleId/edit': typeof AppArticlesArticleIdEditRoute
  '/permissions/roles/create': typeof AppPermissionsRolesCreateRoute
  '/permissions/users/create': typeof AppPermissionsUsersCreateRoute
  '/articles/$articleId/': typeof AppArticlesArticleIdIndexRoute
  '/permissions/roles/': typeof AppPermissionsRolesIndexRoute
  '/permissions/users/': typeof AppPermissionsUsersIndexRoute
  '/permissions/roles/$roleId/edit': typeof AppPermissionsRolesRoleIdEditRoute
  '/permissions/users/$userId/edit': typeof AppPermissionsUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/hero': typeof HeroRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/documentation': typeof AppDocumentationRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/articles/create': typeof AppArticlesCreateRoute
  '/playground/nav1-1': typeof AppPlaygroundNav11Route
  '/playground/nav1-1-1': typeof AppPlaygroundNav111Route
  '/playground/nav1-1-2': typeof AppPlaygroundNav112Route
  '/playground/nav1-2': typeof AppPlaygroundNav12Route
  '/articles': typeof AppArticlesIndexRoute
  '/permissions': typeof AppPermissionsIndexRoute
  '/articles/$articleId/edit': typeof AppArticlesArticleIdEditRoute
  '/permissions/roles/create': typeof AppPermissionsRolesCreateRoute
  '/permissions/users/create': typeof AppPermissionsUsersCreateRoute
  '/articles/$articleId': typeof AppArticlesArticleIdIndexRoute
  '/permissions/roles': typeof AppPermissionsRolesIndexRoute
  '/permissions/users': typeof AppPermissionsUsersIndexRoute
  '/permissions/roles/$roleId/edit': typeof AppPermissionsRolesRoleIdEditRoute
  '/permissions/users/$userId/edit': typeof AppPermissionsUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/hero': typeof HeroRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/articles': typeof AppArticlesRouteWithChildren
  '/_app/documentation': typeof AppDocumentationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/articles/create': typeof AppArticlesCreateRoute
  '/_app/permissions/roles': typeof AppPermissionsRolesRouteWithChildren
  '/_app/permissions/users': typeof AppPermissionsUsersRouteWithChildren
  '/_app/playground/nav1-1': typeof AppPlaygroundNav11Route
  '/_app/playground/nav1-1-1': typeof AppPlaygroundNav111Route
  '/_app/playground/nav1-1-2': typeof AppPlaygroundNav112Route
  '/_app/playground/nav1-2': typeof AppPlaygroundNav12Route
  '/_app/articles/': typeof AppArticlesIndexRoute
  '/_app/permissions/': typeof AppPermissionsIndexRoute
  '/_app/articles/$articleId/edit': typeof AppArticlesArticleIdEditRoute
  '/_app/permissions/roles/create': typeof AppPermissionsRolesCreateRoute
  '/_app/permissions/users/create': typeof AppPermissionsUsersCreateRoute
  '/_app/articles/$articleId/': typeof AppArticlesArticleIdIndexRoute
  '/_app/permissions/roles/': typeof AppPermissionsRolesIndexRoute
  '/_app/permissions/users/': typeof AppPermissionsUsersIndexRoute
  '/_app/permissions/roles/$roleId/edit': typeof AppPermissionsRolesRoleIdEditRoute
  '/_app/permissions/users/$userId/edit': typeof AppPermissionsUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hero'
    | '/login'
    | '/register'
    | '/articles'
    | '/documentation'
    | '/settings'
    | '/articles/create'
    | '/permissions/roles'
    | '/permissions/users'
    | '/playground/nav1-1'
    | '/playground/nav1-1-1'
    | '/playground/nav1-1-2'
    | '/playground/nav1-2'
    | '/articles/'
    | '/permissions/'
    | '/articles/$articleId/edit'
    | '/permissions/roles/create'
    | '/permissions/users/create'
    | '/articles/$articleId/'
    | '/permissions/roles/'
    | '/permissions/users/'
    | '/permissions/roles/$roleId/edit'
    | '/permissions/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hero'
    | '/login'
    | '/register'
    | '/documentation'
    | '/settings'
    | '/'
    | '/articles/create'
    | '/playground/nav1-1'
    | '/playground/nav1-1-1'
    | '/playground/nav1-1-2'
    | '/playground/nav1-2'
    | '/articles'
    | '/permissions'
    | '/articles/$articleId/edit'
    | '/permissions/roles/create'
    | '/permissions/users/create'
    | '/articles/$articleId'
    | '/permissions/roles'
    | '/permissions/users'
    | '/permissions/roles/$roleId/edit'
    | '/permissions/users/$userId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/hero'
    | '/login'
    | '/register'
    | '/_app/articles'
    | '/_app/documentation'
    | '/_app/settings'
    | '/_app/'
    | '/_app/articles/create'
    | '/_app/permissions/roles'
    | '/_app/permissions/users'
    | '/_app/playground/nav1-1'
    | '/_app/playground/nav1-1-1'
    | '/_app/playground/nav1-1-2'
    | '/_app/playground/nav1-2'
    | '/_app/articles/'
    | '/_app/permissions/'
    | '/_app/articles/$articleId/edit'
    | '/_app/permissions/roles/create'
    | '/_app/permissions/users/create'
    | '/_app/articles/$articleId/'
    | '/_app/permissions/roles/'
    | '/_app/permissions/users/'
    | '/_app/permissions/roles/$roleId/edit'
    | '/_app/permissions/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  HeroRoute: typeof HeroRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero': {
      id: '/hero'
      path: '/hero'
      fullPath: '/hero'
      preLoaderRoute: typeof HeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentation': {
      id: '/_app/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles': {
      id: '/_app/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions/': {
      id: '/_app/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AppPermissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/': {
      id: '/_app/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppArticlesRoute
    }
    '/_app/playground/nav1-2': {
      id: '/_app/playground/nav1-2'
      path: '/playground/nav1-2'
      fullPath: '/playground/nav1-2'
      preLoaderRoute: typeof AppPlaygroundNav12RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/nav1-1-2': {
      id: '/_app/playground/nav1-1-2'
      path: '/playground/nav1-1-2'
      fullPath: '/playground/nav1-1-2'
      preLoaderRoute: typeof AppPlaygroundNav112RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/nav1-1-1': {
      id: '/_app/playground/nav1-1-1'
      path: '/playground/nav1-1-1'
      fullPath: '/playground/nav1-1-1'
      preLoaderRoute: typeof AppPlaygroundNav111RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/nav1-1': {
      id: '/_app/playground/nav1-1'
      path: '/playground/nav1-1'
      fullPath: '/playground/nav1-1'
      preLoaderRoute: typeof AppPlaygroundNav11RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions/users': {
      id: '/_app/permissions/users'
      path: '/permissions/users'
      fullPath: '/permissions/users'
      preLoaderRoute: typeof AppPermissionsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions/roles': {
      id: '/_app/permissions/roles'
      path: '/permissions/roles'
      fullPath: '/permissions/roles'
      preLoaderRoute: typeof AppPermissionsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/create': {
      id: '/_app/articles/create'
      path: '/create'
      fullPath: '/articles/create'
      preLoaderRoute: typeof AppArticlesCreateRouteImport
      parentRoute: typeof AppArticlesRoute
    }
    '/_app/permissions/users/': {
      id: '/_app/permissions/users/'
      path: '/'
      fullPath: '/permissions/users/'
      preLoaderRoute: typeof AppPermissionsUsersIndexRouteImport
      parentRoute: typeof AppPermissionsUsersRoute
    }
    '/_app/permissions/roles/': {
      id: '/_app/permissions/roles/'
      path: '/'
      fullPath: '/permissions/roles/'
      preLoaderRoute: typeof AppPermissionsRolesIndexRouteImport
      parentRoute: typeof AppPermissionsRolesRoute
    }
    '/_app/articles/$articleId/': {
      id: '/_app/articles/$articleId/'
      path: '/$articleId'
      fullPath: '/articles/$articleId/'
      preLoaderRoute: typeof AppArticlesArticleIdIndexRouteImport
      parentRoute: typeof AppArticlesRoute
    }
    '/_app/permissions/users/create': {
      id: '/_app/permissions/users/create'
      path: '/create'
      fullPath: '/permissions/users/create'
      preLoaderRoute: typeof AppPermissionsUsersCreateRouteImport
      parentRoute: typeof AppPermissionsUsersRoute
    }
    '/_app/permissions/roles/create': {
      id: '/_app/permissions/roles/create'
      path: '/create'
      fullPath: '/permissions/roles/create'
      preLoaderRoute: typeof AppPermissionsRolesCreateRouteImport
      parentRoute: typeof AppPermissionsRolesRoute
    }
    '/_app/articles/$articleId/edit': {
      id: '/_app/articles/$articleId/edit'
      path: '/$articleId/edit'
      fullPath: '/articles/$articleId/edit'
      preLoaderRoute: typeof AppArticlesArticleIdEditRouteImport
      parentRoute: typeof AppArticlesRoute
    }
    '/_app/permissions/users/$userId/edit': {
      id: '/_app/permissions/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/permissions/users/$userId/edit'
      preLoaderRoute: typeof AppPermissionsUsersUserIdEditRouteImport
      parentRoute: typeof AppPermissionsUsersRoute
    }
    '/_app/permissions/roles/$roleId/edit': {
      id: '/_app/permissions/roles/$roleId/edit'
      path: '/$roleId/edit'
      fullPath: '/permissions/roles/$roleId/edit'
      preLoaderRoute: typeof AppPermissionsRolesRoleIdEditRouteImport
      parentRoute: typeof AppPermissionsRolesRoute
    }
  }
}

interface AppArticlesRouteChildren {
  AppArticlesCreateRoute: typeof AppArticlesCreateRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
  AppArticlesArticleIdEditRoute: typeof AppArticlesArticleIdEditRoute
  AppArticlesArticleIdIndexRoute: typeof AppArticlesArticleIdIndexRoute
}

const AppArticlesRouteChildren: AppArticlesRouteChildren = {
  AppArticlesCreateRoute: AppArticlesCreateRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
  AppArticlesArticleIdEditRoute: AppArticlesArticleIdEditRoute,
  AppArticlesArticleIdIndexRoute: AppArticlesArticleIdIndexRoute,
}

const AppArticlesRouteWithChildren = AppArticlesRoute._addFileChildren(
  AppArticlesRouteChildren,
)

interface AppPermissionsRolesRouteChildren {
  AppPermissionsRolesCreateRoute: typeof AppPermissionsRolesCreateRoute
  AppPermissionsRolesIndexRoute: typeof AppPermissionsRolesIndexRoute
  AppPermissionsRolesRoleIdEditRoute: typeof AppPermissionsRolesRoleIdEditRoute
}

const AppPermissionsRolesRouteChildren: AppPermissionsRolesRouteChildren = {
  AppPermissionsRolesCreateRoute: AppPermissionsRolesCreateRoute,
  AppPermissionsRolesIndexRoute: AppPermissionsRolesIndexRoute,
  AppPermissionsRolesRoleIdEditRoute: AppPermissionsRolesRoleIdEditRoute,
}

const AppPermissionsRolesRouteWithChildren =
  AppPermissionsRolesRoute._addFileChildren(AppPermissionsRolesRouteChildren)

interface AppPermissionsUsersRouteChildren {
  AppPermissionsUsersCreateRoute: typeof AppPermissionsUsersCreateRoute
  AppPermissionsUsersIndexRoute: typeof AppPermissionsUsersIndexRoute
  AppPermissionsUsersUserIdEditRoute: typeof AppPermissionsUsersUserIdEditRoute
}

const AppPermissionsUsersRouteChildren: AppPermissionsUsersRouteChildren = {
  AppPermissionsUsersCreateRoute: AppPermissionsUsersCreateRoute,
  AppPermissionsUsersIndexRoute: AppPermissionsUsersIndexRoute,
  AppPermissionsUsersUserIdEditRoute: AppPermissionsUsersUserIdEditRoute,
}

const AppPermissionsUsersRouteWithChildren =
  AppPermissionsUsersRoute._addFileChildren(AppPermissionsUsersRouteChildren)

interface AppRouteChildren {
  AppArticlesRoute: typeof AppArticlesRouteWithChildren
  AppDocumentationRoute: typeof AppDocumentationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPermissionsRolesRoute: typeof AppPermissionsRolesRouteWithChildren
  AppPermissionsUsersRoute: typeof AppPermissionsUsersRouteWithChildren
  AppPlaygroundNav11Route: typeof AppPlaygroundNav11Route
  AppPlaygroundNav111Route: typeof AppPlaygroundNav111Route
  AppPlaygroundNav112Route: typeof AppPlaygroundNav112Route
  AppPlaygroundNav12Route: typeof AppPlaygroundNav12Route
  AppPermissionsIndexRoute: typeof AppPermissionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArticlesRoute: AppArticlesRouteWithChildren,
  AppDocumentationRoute: AppDocumentationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPermissionsRolesRoute: AppPermissionsRolesRouteWithChildren,
  AppPermissionsUsersRoute: AppPermissionsUsersRouteWithChildren,
  AppPlaygroundNav11Route: AppPlaygroundNav11Route,
  AppPlaygroundNav111Route: AppPlaygroundNav111Route,
  AppPlaygroundNav112Route: AppPlaygroundNav112Route,
  AppPlaygroundNav12Route: AppPlaygroundNav12Route,
  AppPermissionsIndexRoute: AppPermissionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  HeroRoute: HeroRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
