ktor:
  deployment:
    port: 8080
    watch:
      - classes
  application:
    modules:
      # Main Plugins
      - net.axcira.ApplicationKt.main
      - net.axcira.plugins.SerializationKt.configureSerialization
      - net.axcira.features.auth.AuthenticationKt.configureAuthentication
      - net.axcira.plugins.DatabasesKt.configureDatabase
      - net.axcira.plugins.OpenApiKt.configureOpenApi
      - net.axcira.plugins.RoutingKt.root

      # Features
      - net.axcira.features.auth.AuthRoutingKt.auth
      - net.axcira.features.users.UserRoutingKt.users
    dependencies:
      - net.axcira.plugins.DatabasesKt.database
